version: '3.8'

services:
    db:
        container_name: db
        platform: linux/amd64
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
    
    api:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_USER=user
            - DB_PASSWORD=password
            - DB_NAME=mydb
        volumes:
            - ./app:/app
        depends_on:
            - db
volumes:
    db_data:
